countries = [" Afghanistan "," Australia "," Bangladesh "," Bermuda "," Canada "," East Africa "," England "," Hong Kong "," India "," Ireland "," Kenya "," Namibia "," Netherlands "," New Zealand "," P.N.G. "," Pakistan "," Scotland "," South Africa "," Sri Lanka "," U.A.E. "," U.S.A. "," West Indies "," Zimbabwe "]

groundNames = [
         " Aberdeen ",
         " Abu Dhabi ",
           " Adelaide ",
           " Ahmedabad ",
           " Albion ",
           " Albury ",
           " Amritsar ",
           " Amstelveen ",
           " Auckland ",
           " Ayr ",
           " Ballarat ",
           " Basseterre ",
           " Belfast ",
           " Bengaluru ",
           " Benoni ",
           " Berri ",
           " Birmingham ",
           " Bloemfontein ",
           " Bogra ",
           " Bridgetown ",
           " Brisbane ",
           " Bristol ",
           " Bulawayo ",
           " Cairns ",
           " Canberra ",
           " Canterbury ",
           " Cape Town ",
           " Cardiff ",
           " Castries ",
           " Centurion ",
           " Chandigarh ",
           " Chelmsford ",
           " Chennai ",
           " Chester ",
           " Chittagong ",
           " Christchurch ",
           " Colombo ",
           " Cuttack ",
           " Dambulla ",
           " Darwin ",
           " Delhi ",
           " Derby ",
           " Devonport ",
           " Dhaka ",
           " Dharamsala ",
           " Dubai ",
           " Dublin ",
           " Dunedin ",
           " Durban ",
           " East London ",
           " Edinburgh ",
           " Faisalabad ",
           " Faridabad ",
           " Fatullah ",
           " Galle ",
           " Georgetown ",
           " Glasgow ",
           " Greater Noida ",
           " Gros Islet ",
           " Gujranwala ",
           " Guwahati ",
           " Gwalior ",
           " Hambantota ",
           " Hamilton ",
           " Harare ",
           " Hobart ",
           " Hove ",
           " Hyderabad ",
           " ICCA Dubai ",
           " Indore ",
           " Jaipur ",
           " Jalandhar ",
           " Jamshedpur ",
           " Jodhpur ",
           " Johannesburg ",
           " Kandy ",
           " Kanpur ",
           " Karachi ",
           " Khulna ",
           " Kimberley ",
           " King City ",
           " Kingston ",
           " Kingstown ",
           " Kochi ",
           " Kolkata ",
           " Kuala Lumpur ",
           " Kwekwe ",
           " Lahore ",
           " Launceston ",
           " Leeds ",
           " Leicester ",
           " Lincoln ",
           " Lord's ",
           " Lucknow ",
           " Manchester ",
           " Margao ",
           " Melbourne ",
           " Mohali ",
           " Mombasa ",
           " Mong Kok ",
           " Moratuwa ",
           " Mount Maunganui ",
           " Multan ",
           " Mumbai ",
           " Nagpur ",
           " Nairobi ",        
           " Napier ",
           " Nelson ",
           " New Delhi ",
           " New Plymouth ",
           " North Sound ",
           " Northampton ",
           " Nottingham ",
           " Paarl ",
           " Pallekele ",
           " Patna ",
           " Perth ",
           " Pietermaritzburg ",
           " Port Elizabeth ",
           " Port Moresby ",
           " Port of Spain ",
           " Potchefstroom ",
           " Providence ",
           " Pune ",
           " Queenstown ",
           " Quetta ",
           " Rajkot ",
           " Ranchi ",
           " Rawalpindi ",
           " Roseau ",
           " Rotterdam ",
           " Sahiwal ",
           " Sargodha ",
           " Scarborough ",
           " Sharjah ",
           " Sheikhupura ",
           " Sialkot ",
           " Singapore ",
           " Southampton ",
           " Srinagar ",
           " St George's ",
           " St John's ",
           " Swansea" ,
           " Sydney ",
           " Tangier ",
           " Taunton ",
           " Taupo ",
           " The Hague ",
           " The Oval ",
           " Thiruvananthapuram ",
           " Toronto ",
           " Townsville ",
           " Tunbridge Wells ",
           " Vadodara ",
           " Vijayawada ",
           " Visakhapatnam ",
           " Wellington ",
           " Whangarei ",
           " Worcester "
    ]